### ISSUE TITLE
Failure in certain queries

### ISSUE THREAD

**Issue by jiacheng-xu** [Manwholikespie/thesaurus#18]
>>> th.Word('?').synonyms('all',relevance=[3])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    th.Word('?').synonyms('all',relevance=[3])
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/thesaurus/thesaurus.py", line 230, in __init__
    self.data = fetchWordData(inputWord)
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/thesaurus/thesaurus.py", line 142, in fetchWordData
    for defn in data['searchData']['tunaApiData']['posTabs']:
TypeError: list indices must be integers or slices, not str

**Comment by Manwholikespie** [comment]
Thanks for the info. I'm assuming this is because the WordNotFound exception didn't trigger.
Sadly, a lawyer emailed me last week saying I gotta delete this. Farewell, my sweet child.
